defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - vendor
  - script
  - README.md
  - deploy_prev.sh
  - deploy_public.sh
  - invbatch.json
  - create_invalidation_json.py
  - Gemfile
  - Gemfile.lock