backend:
  name: github
  repo: mrxder/WebsiteMalaika
  branch: master # Branch to update (optional; defaults to master)
  #api_root: https://api.github.com
  #auth_endpoint: https://elated-hawking-48f2fe.netlify.app/.netlify/identity

media_folder: "assets/img"

collections:
  - label: "Text"
    name: "text"
    files:
      - label: "All Text"
        name: "allText"
        file: "_data/text2.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: code}