# This is a basic workflow to help you get started with Actions

name: CI/CD production

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: chrislennon/action-aws-cli@v1.1

      # Runs a set of commands using the runners shell
      - name: Build and deploy
        run: |
          bundle exec jekyll build
          aws s3 sync _site s3://www.malaika.cc --exclude prev --exclude SPE
          python3 create_invalidation_json.py _site > invbatch.json
          aws cloudfront create-invalidation --distribution-id E2FUHQH2ML2REJ --invalidation-batch file://invbatch.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
