name: CI/CD production

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: chrislennon/action-aws-cli@v1.1

      - name: Build and deploy
        run: |
          bundle install
          rm -f Gemfile.lock
          bundle exec jekyll build
          aws s3 sync _site s3://www.malaika.cc --exclude prev --exclude SPE
          python3 create_invalidation_json.py _site > invbatch.json
          aws cloudfront create-invalidation --distribution-id E2FUHQH2ML2REJ --invalidation-batch file://invbatch.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
